### ISSUE TITLE
WSL下编译失败, 抛出YAMLException

### ISSUE THREAD

**Issue by zhmushan** [wuhan2020/wuhan2020.github.io#108]
环境:
- nodejs: v12.15.0
- os: ubuntu(WSL)

错误信息:
```sh
┌─[zhmushan@zhmushan-surface-go] - [/mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io] - [2020-02-06 03:32:32]
└─[0] npm run build

> site@0.0.1 build /mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io
> docsite build

YAMLException: bad indentation of a mapping entry at line 14, column 2:
     community:
     ^
    at generateError (/mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:167:          10)
    at throwError (/mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)               at readBlockMapping (/mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1          107:7)
    at composeNode (/mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1359:1          2)
    at readDocument (/mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1519:          3)
    at loadDocuments (/mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1575          :5)
    at load (/mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)                   at Object.safeLoad (/mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:16          18:10)
    at Object.<anonymous> (/mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/docsite/lib/generateHTMLFile.          js:34:26)
    at Module._compile (internal/modules/cjs/loader.js:955:30) {
  name: 'YAMLException',
  reason: 'bad indentation of a mapping entry',
  mark: Mark {
    name: null,
    buffer: 'pages:\n' +
      '  # key is the dirname of pages in src/pages\n' +
      '  home:\n' +
      '    # 首页配置\n' +
      '    zh-cn:\n' +
      "      title: 'Wuhan2020'\n" +
      "      keywords: '官网,首页'\n" +
      "      description: 'Wuhan2020官网'\n" +
      '    # home config\n' +
      '    en-us:\n' +
      "      title: 'Wuhan2020'\n" +
      "      keywords: 'Official,Wuhan2020'\n" +
      "      description: 'Wuhan2020 Official Website'\n" +
      ' community:\n' +
      '    # 社区页配置\n' +
      '    zh-cn:\n' +
      "      title: '社区'\n" +
      "      keywords: 'Wuhan2020,社区'\n" +
      "      description: 'Wuhan2020社区'\n" +
      '    # community page config\n' +
      '    en-us:\n' +
      "      title: 'Community'\n" +
      "      keywords: 'Seata,Community'\n" +
      "      description: 'Seata Community'\n" +
      '  blog:\n' +
      '    # 博客列表页配置\n' +
      '    zh-cn:\n' +
      "      title: '博客'\n" +
      "      keywords: 'Wuhan2020,博客'\n" +
      "      description: 'Wuhan2020 博客'\n" +
      '    # blog list page config\n' +
      '    en-us:\n' +
      "      title: 'Blog'\n" +
      "      keywords: 'Wuhan2020,Blog'\n" +
      "      description: 'Wuhan2020 Blog'\n" +
      '\u0000',
    position: 304,
    line: 13,
    column: 1
  },
  message: 'bad indentation of a mapping entry at line 14, column 2:\n' +
    '     community:\n' +
    '     ^'
}
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Module._compile (/mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Object.newLoader [as .js] (/mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/pirates/lib/index.js:104:7)         at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
```

**Comment by zhmushan** [comment]
补充依赖安装信息:
```sh
┌─[zhmushan@zhmushan-surface-go] - [/mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io] - [2020-02-06 03:28:01]
└─[130] npm i
npm WARN deprecated extract-text-webpack-plugin@2.1.2: Deprecated. Please use https://github.com/webpack-contrib/mini-c          ss-extract-plugin
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.          com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.c          om/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number           of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use i          t, and update to graceful-fs@4.x.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number o          f issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versio          ns of Node.js

> node-sass@4.13.1 install /mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-72_binding.node
Download complete..] - :
Binary saved to /mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/node-sass/vendor/linux-x64-72/binding.no          de
Caching binary to /home/zhmushan/.npm/node-sass/4.13.1/linux-x64-72_binding.node

> core-js@2.6.11 postinstall /mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall /mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> node-sass@4.13.1 postinstall /mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/node-sass
> node scripts/build.js

Binary found at /mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/node-sass/vendor/linux-x64-72/binding.no          de
Testing binary
Binary is fine

> docsite@1.3.9-wuhan2020.5 postinstall /mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/docsite
> opencollective-postinstall

Thank you for using docsite!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/docsite/donate

npm WARN rollback Rolling back node-pre-gyp@0.14.0 failed (this is probably harmless): EINVAL: invalid argument, scandi          r '/mnt/c/Users/zhmushan/Desktop/wuhan2020.github.io/node_modules/fsevents/node_modules'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN file-loader@3.0.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies           yourself.
npm WARN eslint-config-ali@1.0.3 requires a peer of eslint@^3.6.0 but none is installed. You must install peer dependen          cies yourself.
npm WARN eslint-config-ali@1.0.3 requires a peer of eslint-plugin-import@^1.16.0 but none is installed. You must instal          l peer dependencies yourself.
npm WARN eslint-config-ali@1.0.3 requires a peer of eslint-plugin-react@^6.3.0 but none is installed. You must install           peer dependencies yourself.
npm WARN acorn-jsx@5.1.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer depende          ncies yourself.
npm WARN The package react is included as both a dev and production dependency.
npm WARN The package react-dom is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"a          ny"} (current: {"os":"linux","arch":"x64"})

added 1423 packages from 1045 contributors and audited 20082 packages in 266.242s

28 packages are looking for funding
  run `npm fund` for details

found 7 vulnerabilities (1 low, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by purple-force** [comment]
1. yaml 14行缩进可能有问题 2. 当前工程依赖还不支持node12，降到10

**Comment by zhmushan** [comment]
> 1. yaml 14行缩进可能有问题 2. 当前工程依赖还不支持node12，降到10

谢谢！那应该就是nodejs版本问题了
