### ISSUE TITLE
Can't Start The Local Server

### ISSUE THREAD

**Issue by iLtc** [wuhan2020/wuhan2020.github.io#214]
## 当前问题

更新了最新的代码后，IDE 提示我 package.json 有变化，于是我顺便更新了所有包，之后无法启动本地服务器，报以下错误。

```
[10:48:04] Using gulpfile ~/Downloads/wuhan2020.github.io-dev/gulpfile.js
[10:48:04] Starting 'webpack-dev-server'...
[10:48:04] 'webpack-dev-server' errored after 71 ms
[10:48:04] TypeError: Cannot read property 'entryOption' of undefined
    at compilers.forEach (/Users/iltc/Downloads/wuhan2020.github.io-dev/node_modules/webpack-dev-server/lib/utils/updateCompiler.js:51:22)
    at Array.forEach (<anonymous>)
    at updateCompiler (/Users/iltc/Downloads/wuhan2020.github.io-dev/node_modules/webpack-dev-server/lib/utils/updateCompiler.js:49:15)
    at new Server (/Users/iltc/Downloads/wuhan2020.github.io-dev/node_modules/webpack-dev-server/lib/Server.js:72:5)
    at Gulp.gulp.task (/Users/iltc/Downloads/wuhan2020.github.io-dev/gulpfile.js:23:3)
    at module.exports (/Users/iltc/Downloads/wuhan2020.github.io-dev/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/iltc/Downloads/wuhan2020.github.io-dev/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/iltc/Downloads/wuhan2020.github.io-dev/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/iltc/Downloads/wuhan2020.github.io-dev/node_modules/orchestrator/index.js:134:8)
    at /Users/iltc/Downloads/wuhan2020.github.io-dev/node_modules/gulp/bin/gulp.js:129:20
```

随后我重新下载了整个项目的最新代码，再次安装依赖，启动时仍然出现以上错误。

复现步骤：

```
git clone git@github.com:wuhan2020/wuhan2020.github.io.git
cd wuhan2020.github.io.git
npm i docsite@wuhan2020 -g
npm i
docsite start
```

## 期待的正确输出

可以启动服务器

**Comment by GindaChen** [comment]
@chenrui333

**Comment by chenrui333** [comment]
这可能跟我上次upgrade dev server 有关系

我revert看看

**Comment by iLtc** [comment]
@chenrui333 我把本地的 webpack-dev-server 换成 ^2.4.5 可以正常启动

**Comment by chenrui333** [comment]
make total sense.

**Comment by chenrui333** [comment]
revert is done.
