### ISSUE TITLE
本地启动报错

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020.github.io#458]
## 当前问题
请描述清楚你使用的环境，最好有相应的截图以便我们重现问题

```log
 npm run start      

> site@0.0.1 start /Users/wx/workspace/wuhan2020.github.io
> docsite start

(node:10194) UnhandledPromiseRejectionWarning: SecurityError: localStorage is not available for opaque origins
    at Window.localStorage (/Users/wx/workspace/wuhan2020.github.io/node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
    at new GitalkComponent (/Users/wx/workspace/wuhan2020.github.io/node_modules/gitalk/dist/webpack:/gitalk.jsx:84:34)
    at processChild (/Users/wx/workspace/wuhan2020.github.io/node_modules/react-dom/cjs/react-dom-server.node.development.js:2995:14)
    at resolve (/Users/wx/workspace/wuhan2020.github.io/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/Users/wx/workspace/wuhan2020.github.io/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/Users/wx/workspace/wuhan2020.github.io/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at Object.renderToString (/Users/wx/workspace/wuhan2020.github.io/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at files.forEach.file (/Users/wx/workspace/wuhan2020.github.io/node_modules/docsite/lib/generateJSONFile.js:87:38)
    at Array.forEach (<anonymous>)
    at parse (/Users/wx/workspace/wuhan2020.github.io/node_modules/docsite/lib/generateJSONFile.js:39:11)
(node:10194) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10194) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js proce
```

**Comment by jeremy0519** [comment]
是gitalk的原因，把那个revert掉就好了

**Comment by lovepoem** [comment]
> 是gitalk的原因，把那个revert掉就好了

最好能查一下适应性的问题。现在线上站点运行正常，就先不用revert 了

**Comment by lovepoem** [comment]
Convert没有解决，看起来和gitalk有关

**Comment by jeremy0519** [comment]
是和gitalk有关，应该是什么地方没有引入

**Comment by jeremy0519** [comment]
在npm安装后
