### ISSUE TITLE
npm run  start 报错

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020.github.io#462]
## 当前问题
请描述清楚你使用的环境，最好有相应的截图以便我们重现问题

```log


[14:32:05] TypeError: Cannot read property 'entryOption' of undefined
    at compilers.forEach (/Users/wx/workspace/wuhan2020.github.io/node_modules/webpack-dev-server/lib/utils/updateCompiler.js:51:22)
    at Array.forEach (<anonymous>)
    at updateCompiler (/Users/wx/workspace/wuhan2020.github.io/node_modules/webpack-dev-server/lib/utils/updateCompiler.js:49:15)
    at new Server (/Users/wx/workspace/wuhan2020.github.io/node_modules/webpack-dev-server/lib/Server.js:72:5)
    at Gulp.gulp.task (/Users/wx/workspace/wuhan2020.github.io/gulpfile.js:23:3)
    at module.exports (/Users/wx/workspace/wuhan2020.github.io/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/wx/workspace/wuhan2020.github.io/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/wx/workspace/wuhan2020.github.io/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/wx/workspace/wuhan2020.github.io/node_modules/orchestrator/index.js:134:8)
    at /Users/wx/workspace/wuhan2020.github.io/node_modules/gulp/bin/gulp.js:129:20



```

**Comment by jeremy0519** [comment]
我也是

**Comment by zhaofeng-shu33** [comment]
But the latest deployment succeeds.

**Comment by lovepoem** [comment]
webpack-dev-server 需要再revert回去老版本

**Comment by lovepoem** [comment]
@purple-force 这个怎么能升级上去？

**Comment by zhaofeng-shu33** [comment]
Which version of webpack-dev-server should be used?

**Comment by lovepoem** [comment]
> Which version of webpack-dev-server should be used?

revert pr : https://github.com/wuhan2020/wuhan2020.github.io/pull/463

**Comment by zhaofeng-shu33** [comment]
I encounter the same problem when `package_lock.json` and `node_modules` are removed.

**Comment by pengcc** [comment]
Don't just update something unless you have tested it through. I would not recommend upgrading the webpack and related references currently. The version information about the debpack-dev-sever can be found here, https://www.npmjs.com/package/webpack-dev-server.  On the frontend side, there are code smells. They must be cleaned up firstly. Code Quality is important. And the latest version doesn't mean it will the best one. The webpack 4 is a major upgrade so as the webpack-dev-server. They are not promised backwards compatibility. It's a hard work to upgrade webpack. There are a lot of deprecated plugins that have been removed from the webpack 4 and obviously they must be replaced by the new plugins in this project.
